/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class evenFibonacci{

	public static void main(String[] args){
		new evenFibonacci();
	}

	public evenFibonacci(){
		int countNumber = 0;
		int currentNum = 2;
		int pastNum = 1;
		int tempNum;
		while(currentNum < 4000000){
			if(currentNum % 2 == 0){
				countNumber += currentNum;
			}
			tempNum = currentNum;
			currentNum += pastNum;
			pastNum = tempNum;
		}
		System.out.println(countNumber);
	}

}